Fix Firefox can't click on links: rename globalThis to window
Introduced in f5a0a262686d9590f053c19bba0973ffdcb08975

This happens in Firefox but not Chrome when clicking a link with link hints:

TypeError: MouseEvent constructor: 'view' member of UIEventInit does not implement interface Window.